#!/bin/sh

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

yadm decrypt || 
(
  export GPG_TTY=$(tty) && 
  yadm decrypt ||
  echo unable to decrypt, continuing
)

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:overclockedllama/dotfiles.git"

echo "Init submodules"
yadm submodule update --recursive --init

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
    if ! command -v brew >/dev/null 2>&1; then
        echo "Installing homebrew"
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi
    
    echo -n "Please enter if you would like to install ALL of overclockedllama's programs (y/n)? "
    read answer
    if [ "$answer" != "${answer#[Yy]}" ] ;then
        if [ -f "$HOME/.config/brewfile" ]; then
            echo "Updating homebrew bundle"
            brew bundle --file=~/.config/brewfile
        fi
    else
        brew install vim zsh-autosuggestions zsh-syntax-highlighting
        brew cask install visual-studio-code
    fi


    if [ -d "$HOME/.config/iterm2" ]; then
        echo "Setting iTerm preference folder"
        defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.config/iterm2"
    fi
fi

if command -v apt-get >/dev/null 2>&1; then
    apt-get update
    apt-get install vim zsh-autosuggestions zsh-syntax-highlighting zsh
fi

if command -v pacman >/dev/null 2>&1; then
    pacman -Syu vim zsh-autosuggestions zsh-syntax-highlighting zsh
fi



