#!/bin/sh

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

yadm decrypt || 
(
  export GPG_TTY=$(tty) && 
  yadm decrypt
)

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:overclockedllama/dotfiles.git"

echo "Init submodules"
yadm submodule update --recursive --init

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.config/brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --file=~/.config/brewfile
  fi
  if [ -d "$HOME/.config/iterm2" ]; then
    echo "Setting iTerm preference folder"
    defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.config/iterm2"
  fi
fi
